"""Configuration for Sphinx documentation."""
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
PACKAGE_ROOT = os.path.join(os.path.dirname(__file__), '..')
sys.path.insert(0, os.path.join(PACKAGE_ROOT, 'src'))


# -- Project information -----------------------------------------------------

project = 'olsen-randerson'
copyright = '2019, DWesl'  # noqa: A001
author = 'DWesl'

# The full version, including alpha/beta/rc tags
with open(os.path.join(PACKAGE_ROOT, 'VERSION'), 'r') as version_file:
    release = version_file.read().strip()


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.extlinks',
    'numpydoc',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []


# -- Extension configuration -------------------------------------------------

# Mapping of new roles to sites and substitution prefixes
extlinks = dict(
    doi=("https://dx.doi.org/%s", "doi:"),
    arxiv=("https://arxiv.org/abs/%s", "arxiv:"),
    jstor=("https://www.jstor.org/stable/%s", "jstor:"),
)

# List of regexes linkcheck should ignore
linkcheck_ignore = [r"https://www.jstor.org/stable/\w+"]

# Mathjax configuration
mathjax_config = dict(
    extensions=["tex2jax.js"],
    jax=["input/TeX", "output/HTML-CSS"],
    TeX=dict(
        extensions=["AMSmath.js"],
    ),
)

# Options for numpydoc
numpydoc_xref_param_type = True

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'https://docs.python.org/3/': None,
    'https://docs.scipy.org/doc/numpy/': None,
    'https://pandas.pydata.org/pandas-docs/stable/': None,
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
